
- name: holehe - install/upgrade holehe via pipx
  become: yes
  become_user: "{{ login_user }}"
  community.general.pipx:
    name: holehe
    state: latest       # upgrades if an older version is present
  tags:
    - holehe
    - OSINT

