
- name: OSINT - Copy OSINT_Tools.txt to home directory
  become: false
  copy:
    src: OSINT_Tools.txt
    dest: "{{ login_home }}/OSINT_Tools.txt"
    mode: "0644"
  tags:
    - OSINT

- name: OSINT - Install jq, ripgrep and exiftool
  apt:
    name:
      - jq
      - ripgrep
      - libimage-exiftool-perl
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - jq
    - ripgrep
    - exiftool
    - OSINT

- name: Run - Sherlock setup
  import_tasks: sherlock.yml

- name: Run - Maigret setup
  import_tasks: maigret.yml

- name: Run - Sublist3r setup
  import_tasks: sublist3r.yml

- name: Run - TheHarvester setup
  import_tasks: theharvester.yml

- name: Run - Carbon14 setup
  import_tasks: carbon14.yml

- name: Run - Recon-ng setup
  import_tasks: recon-ng.yml

- name: Run - Spiderfoot setup
  import_tasks: spiderfoot.yml

- name: Run - Change Detection setup
  import_tasks: changedetection.yml

- name: Run - Blackbird setup
  import_tasks: blackbird.yml

- name: Run - WhatsMyName-Python setup
  import_tasks: whatsmyname.yml

- name: Run - Holehe setup
  import_tasks: holehe.yml

- name: Run - sn0int setup
  import_tasks: sn0int.yml

- name: Run - Amass setup
  import_tasks: amass.yml

- name: Run - Maltego setup
  import_tasks: maltego.yml

