
- name: sn0int - ensure prerequisite packages are present
  apt:
    name:
      - curl
      - gnupg
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - sn0int
    - OSINT

- name: sn0int - download kpcyrd signing key
  get_url:
    url: https://apt.vulns.sexy/kpcyrd.pgp
    dest: /usr/share/keyrings/apt-vulns-sexy.gpg
    mode: '0644'
  tags:
    - sn0int
    - OSINT

- name: sn0int - add apt repository
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/apt-vulns-sexy.gpg] http://apt.vulns.sexy stable main"
    filename: apt-vulns-sexy
    state: present
  tags:
    - sn0int
    - OSINT

- name: sn0int - install package
  apt:
    name: sn0int
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - sn0int
    - OSINT

