
- name: sublist3r - install/upgrade sublist3r via pipx
  become: yes
  become_user: "{{ login_user }}"
  community.general.pipx:
    name: sublist3r
    state: latest       # upgrades if an older version is present
  tags:
    - sublist3r
    - OSINT

