
- name: theharvester - install/upgrade theHarvester via pipx
  become: yes
  become_user: "{{ login_user }}"
  community.general.pipx:
    name: theHarvester
    state: latest       # upgrades if an older version is present
  tags:
    - theharvester
    - OSINT

