
- name: Run Mullvad VPN setup
  import_tasks: mullvad.yml

- name: Run n8n setup
  import_tasks: n8n.yml

- name: Run Cursor setup
  import_tasks: cursor.yml

- name: Run Antigravity setup
  import_tasks: antigravity.yml

- name: Run Claude Code setup
  import_tasks: claude-code.yml

- name: Run Tor Browser setup
  import_tasks: tor-browser.yml

- name: Run Terraform setup
  import_tasks: terraform.yml
