- name: torbrowser - Remove legacy Tor Project key (migration from apt_key)
  apt_key:
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: absent
  when: vmware_env == "ubuntu"
  tags:
    - torbrowser
    - privacy

- name: torbrowser - Fetch Tor Project GPG key
  get_url:
    url: https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc
    dest: /tmp/torproject.asc
    mode: '0644'
    force: yes
  when: vmware_env == "ubuntu"
  tags:
    - torbrowser
    - privacy

- name: torbrowser - Dearmor GPG key into keyrings
  command: gpg --dearmor --output /usr/share/keyrings/torproject.gpg /tmp/torproject.asc
  args:
    creates: /usr/share/keyrings/torproject.gpg
  when: vmware_env == "ubuntu"
  tags:
    - torbrowser
    - privacy

- name: torbrowser - Add Tor Project repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/torproject.gpg] https://deb.torproject.org/torproject.org {{ ansible_distribution_release }} main"
    state: present
    filename: tor
  when: vmware_env == "ubuntu"
  tags:
    - torbrowser
    - privacy

- name: torbrowser - Install torbrowser-launcher
  apt:
    name:
      - torbrowser-launcher
    state: present
    update_cache: yes
  when: vmware_env == "ubuntu"
  tags:
    - torbrowser
    - privacy

- name: torbrowser - Install from Kali repos
  apt:
    name:
      - torbrowser-launcher
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: vmware_env != "ubuntu"
  tags:
    - torbrowser
    - privacy