
- name: AD - Copy AD_Tools.txt to home directory
  become: false
  copy:
    src: AD_Tools.txt
    dest: "{{ login_home }}/AD_Tools.txt"
    mode: "0644"
  tags:
    - AD

- name: Run windapsearch setup
  import_tasks: windapsearch.yml

- name: Run SCCMHunter setup
  import_tasks: SCCMHunter.yml

- name: Run BloodhoundCE setup
  import_tasks: BloodhoundCE.yml

- name: Run Certipy setup
  import_tasks: Certipy.yml

- name: Run dploot setup
  import_tasks: dploot.yml

- name: Run DonPAPI setup
  import_tasks: DonPAPI.yml

- name: Run kerbrute setup
  import_tasks: kerbrute.yml

- name: Run ldapx setup
  import_tasks: ldapx.yml

- name: Run bloodhound-python setup
  import_tasks: bloodhound-python.yml

- name: Run BloodyAD setup
  import_tasks: BloodyAD.yml

- name: Run ntdsdotsqlite setup
  import_tasks: ntdsdotsqlite.yml

- name: Run gmsadumper setup
  import_tasks: gmsadumper.yml

- name: Run godap setup
  import_tasks: godap.yml

- name: Run rusthound-ce setup
  import_tasks: rusthound-ce.yml

- name: Run runascs setup
  import_tasks: runascs.yml
