
- name: Network - Copy Network_Tools.txt to home directory
  become: false
  copy:
    src: Network_Tools.txt
    dest: "{{ login_home }}/Network_Tools.txt"
    mode: "0644"
  tags:
    - network

- name: Run Enum4linux-ng setup
  import_tasks: Enum4linux-ng.yml

- name: Run SSH-Audit setup
  import_tasks: SSH-Audit.yml

- name: Run evil-winrm-py setup
  import_tasks: evil-winrm-py.yml


