
- name: ssh-audit - install ssh-audit package
  ansible.builtin.apt:
    name: ssh-audit
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - ssh-audit
    - network